
---

- name: add repo if ubuntu 20.04
  apt_repository:
    repo: ppa:kgilmer/speed-ricer
  register: addppa
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '20.04'

- name: Run apt update
  apt:
    update_cache: yes
    autoclean: yes
  when: addppa.changed

- name: 'Install polybar'
  package:
    name: ['polybar','calc','python3-pip']
    state: present
    install_recommends: yes

- name: update pip
  pip:
    name: pip
    state: latest

- name: install pywall
  pip:
    name: pywal
    state: latest

- name: Create dir for config
  become: no
  file:
    path: ~/.config/polybar
    state: directory
    mode: '0755'

- name: Git checkout Polybar-Themes
  git:
    repo: "{{ git_polybar }}"
    dest: /tmp/polybar-themes
 
- name: Copy theme to config
  become: no
  shell:
    cmd: /tmp/polybar-themes/setup.sh sim && touch ~/.config/i3/.polybarconfiginstalled
    creates: ~/.config/i3/.polybarconfiginstalled

- name: Enable polybar in i3
  become: no
  lineinfile:
    dest: ~/.config/i3/config
    regexp: ".#polybarstartup" 
    line: "exec --no-startup-id ~/.config/polybar/launch.sh --hack #polybarstartup DO NOT REMOVE COMMENT"
