---
# tasks file for develope

- name: install microsoft repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  register: ms_repo_installed
  with_items:
   - deb [arch=amd64] https://packages.microsoft.com/repos/code stable main
   - deb [arch=amd64] https://packages.microsoft.com/repos/edge stable main
   - deb [arch=amd64] https://packages.microsoft.com/repos/ms-teams stable main
   
- name: add microsoft key
  apt_key:
    url: "{{ ms_key }}"
    state: present

- name: Run apt update
  apt:
    update_cache: yes
  when: ms_repo_installed.changed
  
- name: install dev things 
  apt:
    name: "{{ dev_tools }}"
    state: latest
    install_recommends: yes

- name: install Microsoft Teams
  apt:
    name: teams
    state: present
  when: install_ms_teams | bool
  
- block:

  - name: download go 1.15.6
    get_url:
      url: "{{ go_get_url }}"
      dest: /tmp/go.tgz
      checksum: "{{ go_get_checksum }}"

  - name: install go 
    unarchive:
        src: /tmp/go.tgz
        dest: /usr/local
        remote_src: yes
     
  - name: add go to path (you have to run -> source ~/.bashrc)
    become: no
    lineinfile:
        path: ~/.bashrc
        line: 'export PATH=$PATH:/usr/local/go/bin'

  when: install_go_lang | bool

- name: copy vim config
  become: no
  copy:
    src: vimrc
    dest: ~/.vimrc

- name: copy tmux config
  become: no
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf

- name: create tmux config folder
  become: no
  file:
    path: ~/.config/tmux
    state: directory

- name: copy tmux theme
  become: no
  copy:
    src: tmux-power.tmux
    dest: ~/.config/tmux/tmux-power.tmux
    mode: '0755'

- name: create folders for mc
  become: no
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  with_items:
    - "~/.local/share/mc/skins"
    - "~/.config/mc"

- name: copy mc skin file 
  become: no
  copy:
    src: mc-skin
    dest: ~/.local/share/mc/skins/cp-blue-00.ini

- name: copy mc config file
  become: no
  copy:
    src: mc-ini
    dest: ~/.config/mc/ini
